[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn informatik22.wsgi --log-file -"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
