# Generated by Django 5.2.15 on 2026-07-06 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('file', models.FileField(upload_to='materials/', verbose_name='Fayl')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
            ],
            options={
                'verbose_name': "O'qituvchi materiali",
                'verbose_name_plural': "O'qituvchi materiallari",
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Savol')),
                ('option_a', models.CharField(max_length=300, verbose_name='A variant')),
                ('option_b', models.CharField(max_length=300, verbose_name='B variant')),
                ('option_c', models.CharField(max_length=300, verbose_name='C variant')),
                ('option_d', models.CharField(max_length=300, verbose_name='D variant')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name="To'g'ri javob")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
            ],
            options={
                'verbose_name': 'Kunlik test',
                'verbose_name_plural': 'Kunlik testlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name="To'liq ism")),
                ('student_class', models.CharField(blank=True, max_length=50, verbose_name='Sinf')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('points', models.FloatField(default=0.0, verbose_name='Ballar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profillar',
            },
        ),
        migrations.CreateModel(
            name='StudentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Rasm')),
                ('learned_today', models.TextField(verbose_name="Bugun nimani o'rgandim")),
                ('experience', models.TextField(verbose_name='Tajribam')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
            ],
            options={
                'verbose_name': "O'quvchi ishi",
                'verbose_name_plural': "O'quvchilar ishlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
