# Generated by Django 5.2.15 on 2026-07-06 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytest',
            name='solved_by',
            field=models.ManyToManyField(blank=True, related_name='solved_quizzes', to=settings.AUTH_USER_MODEL, verbose_name="Yechgan o'quvchilar"),
        ),
    ]
