# Generated by Django 5.2.15 on 2026-07-06 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dailytest_solved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_quiz_attempt',
            field=models.DateField(blank=True, null=True, verbose_name='Oxirgi test yechgan sana'),
        ),
        migrations.AddField(
            model_name='studentpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='Layklar'),
        ),
    ]
