# Generated by Django 5.2.15 on 2026-07-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_last_quiz_attempt_studentpost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_quiz_count',
            field=models.IntegerField(default=0, verbose_name='Bugungi yechilgan testlar soni'),
        ),
    ]
